version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: software.amazon.awssdk:bom
    versions:
    - 2.15.71
    - 2.15.72
    - 2.15.73
    - 2.15.74
    - 2.15.75
    - 2.15.76
    - 2.15.77
    - 2.15.78
    - 2.15.79
    - 2.15.80
    - 2.15.81
    - 2.15.82
    - 2.16.0
    - 2.16.1
    - 2.16.10
    - 2.16.11
    - 2.16.12
    - 2.16.13
    - 2.16.14
    - 2.16.15
    - 2.16.16
    - 2.16.17
    - 2.16.18
    - 2.16.19
    - 2.16.2
    - 2.16.20
    - 2.16.21
    - 2.16.22
    - 2.16.23
    - 2.16.24
    - 2.16.25
    - 2.16.26
    - 2.16.28
    - 2.16.29
    - 2.16.3
    - 2.16.30
    - 2.16.32
    - 2.16.33
    - 2.16.34
    - 2.16.35
    - 2.16.36
    - 2.16.37
    - 2.16.38
    - 2.16.39
    - 2.16.4
    - 2.16.40
    - 2.16.41
    - 2.16.42
    - 2.16.43
    - 2.16.44
    - 2.16.45
    - 2.16.46
    - 2.16.47
    - 2.16.48
    - 2.16.5
    - 2.16.7
    - 2.16.8
    - 2.16.9
  - dependency-name: org.springframework:spring-context
    versions:
    - 5.3.3
    - 5.3.4
    - 5.3.5
  - dependency-name: com.amazonaws:aws-lambda-java-events
    versions:
    - 3.7.0
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - 4.9.0
