sudo: false
language: java
services:
  - docker
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'


addons:
  sonarcloud:
    organization: "hche608-github" # the key of the org you chose at step #3
    token:
      secure: "${sonar}" # encrypted value of your token

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.organization=hche608-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${sonar} && mvn clean deploy"
  skip_cleanup: true
  on:
    tags: true