sudo: false
language: java
services:
  - docker
cache:
  directories:
  - "$HOME/.cache"

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn clean deploy"
  skip_cleanup: true
  on:
    tags: true
addons:
  sonarcloud:
    organization: "hche608-github" # the key of the org you chose at step #3
    token:
      secure: "${env.sonar}" # encrypted value of your token
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.organization=hche608-github